info:
  contact: {}
  title: RpsChecked
  version: "0.01"
paths:
  /sites:
    get:
      parameters:
      - description: Your query
        in: query
        name: query
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: ""
      summary: Calculate sites rps by query
      tags:
      - SitesController
swagger: "2.0"
